#!/usr/bin/env bash

action "service start" "Starts ${extension} service."
action "service stop" "Stops ${extension} service."
action "service restart" "Restart ${extension} service."
action "service status" "Status of the ${extension} service."

show_help usage

