#!/bin/sh

typeset -g architecture os

mongodb_set_architecture()
{
  case $(os arch capable) in
    (i386|i686)
      architecture="i686"
      ;;

    (x86_64)
      architecture="x86_64"
      ;;

    (*)
      if [[ "$action" = *install ]]
      then
        log fail "Unhandled architecture: $HOSTTYPE for ${extension} ${action}"
      fi
      ;;
  esac
}

mongodb_set_os()
{
  case $(os type) in
    (*linux*)
      os="linux"
      ;;
    (*darwin*)
      os="osx"
      ;;
    (*solaris*)
      os="sunos5"
      if [[ "$architecture" = "i686" ]]
      then architecture="i86pc" ; fi # C'mon Solaris, really???
      ;;
    (*)
      if [[ "$action" = *install ]] ; then
        log fail "Unhandled operating system: $MACHTYPE for ${extension} ${action}"
      fi
      ;;
  esac
}

mongodb_backup()
{
  true # TODO: Implement this
}

