#!/usr/bin/env bash

package_definition \
  file "${package_name}-${package_version}-unix.${archive_format}" # \
  #dir "${package_name}-${package_version}"

#if [[ "${package_version}" == "head" ]]
#then
#  repository_url="git@github.com:neo4j/community.git"
#  # neo4j_build: mvn clean install -Dmaven.test.skip=true
#  package_dependencies=(maven docbook asciidoc w3m fop)
#fi
