#!/usr/bin/env bash

: \
  ${service_port:=5432} \
  ${service_bind_interface:="127.0.0.1"}

service_binary="${service_bin_path}/pg_ctl"
service_cli_binary="${service_bin_path}/psql"
if array_is_empty service_flags
then
  _action="${action//\(*}"
  service_flags+=(${_action//*_} -D "$service_data_path/data" -s )
  service_stop_flags+=( -m fast -w )
fi

if os_is_darwin
then
  service_user="_postgres"
else
  service_user="postgres"
fi

export PGDATA="${service_data_path}/data"

service_pid_file="${service_data_path}/data/postmaster.pid"

