#!/usr/bin/env bash

package_dependencies=(readline)

package_definition \
  base_url "http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v${package_version}"

if user_is_root
then
  if [[ "${package_user}" = "postgresql" || -z ${package_user} ]]
  then
    package_user="postgres"
  fi
else
  package_user="$USER"
  prefix_path="$HOME/.bdsm"
fi

configure_flags=( --with-readline-dir="${active_path}/lib" )

