#!/bin/sh

redis_make_install()
{
  local _source="src/" _major _minor _patch

  _major=${package_version//.*}
  # _patch=${package_version//*.}
  _minor=${package_version%.*}
  _minor=${_minor#*.}

  if (( _major >= 2 ))
  then
    if ! (( _major = 2 && _minor >= 2 ))
    then
      _source=""
    fi
  else
    _source=""
  fi

  # TODO: Install to install_path
  ensure_paths_exist "${install_path}/bin"

  log "#installing ${package_name} ${package_version}...\n"
  for file in redis-server redis-cli
  do
    if ! install -b "${_source}${file}" "${install_path}/bin/${file}"
    then
      fail "${package_name} ${package_version} failed to install (specifically ${file}).\n"
    fi
  done
}

