#!/usr/bin/env bash

mongodb_configure()
{
  true # no-op
}

mongodb_build()
{
  true # no-op
}

mongodb_install()
{
  local file files name

  ensure_paths_exist "${install_path}"

  files=($(
  find "${source_path}/${package_dir}/bin" -mindepth 1 -maxdepth 1 -type f
  ))

  for file in "${files[@]}"
  do
    name=${file//*\/}
    ensure_paths_exist "${install_path}/bin"
    copy_file "${file}" to "${install_path}/bin/${name}" mode 0755
  done
}

mongodb_postinstall()
{
  if path_exists "${install_base_path}"
  then
    return 0
  else
    activate_package "${package_name}" "${package_version}"
  fi
}

mongodb_set_architecture()
{
  case "$(os_arch_capable)" in
    i386|i686)
      architecture="i686"
      ;;

    x86_64)
      architecture="x86_64"
      ;;

    *)
      if [[ "$action" = *install ]] ; then
        fail "Unhandled architecture: $HOSTTYPE for ${extension} ${action}"
      fi
      ;;
  esac
}

mongodb_set_os()
{
  case "$MACHTYPE" in
    *linux*)
      os="linux"
      ;;

    *darwin*)
      os="osx"
      ;;

    *solaris*)
      os="sunos5"
      if [[ "$architecture" = "i686" ]] ; then
        architecture="i86pc" # C'mon Solaris, really???
      fi
      ;;

    *)
      if [[ "$action" = *install ]] ; then
        fail "Unhandled operating system: $MACHTYPE for ${extension} ${action}"
      fi
      ;;
  esac
}

