#!/usr/bin/env bash

# Default service_flags for memcached.
service_flags=(
  -d
  -p ${port:-11212}
  -u "${user:-memcached}"
  -m ${memory:-64}
  -c ${max_connections:-1024}
  -P "${service_pid_file:-"/var/run/memcached/memcached.pid"}"
)
