#!/bin/sh

credis_preinstall()
{
  path enter ${source_path}/credis-${package_version}

  paths create include lib

  file copy from libcredis.so to lib/libcredis.so

  file copy from credis.h to include/credis.h
}
